name: DevSecOps
on: workflow_dispatch

env:
  DOCKER_IMAGE: 'webgoat/webgoat-8.0'

jobs:

  trufflehog_secret_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker pull trufflesecurity/trufflehog:v3.88.34
        docker pull ghcr.io/jqlang/jq:1.7.1

    - name: TruffleHog Scan
      run: |
        {
            echo "["
            first=true
            docker run --rm -v $(pwd):/home trufflesecurity/trufflehog:v3.88.34 filesystem --json /home | while read -r line; do
                if [ "$first" != true ]; then
                    echo ","
                fi

                echo "$line" | docker run --rm ghcr.io/jqlang/jq:1.7.1 .

                first=false
            done
            echo "]"
        } > trufflehog-secrets-report.json
      continue-on-error: true

    - name: Upload TruffleHog Report
      uses: actions/upload-artifact@v4
      with:
        name: trufflehog-secrets-report
        path: trufflehog-secrets-report.json

  semgrep_sast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Semgrep Scan
      run: |
        docker pull semgrep/semgrep:latest
        docker run --rm -v $(pwd):/src semgrep/semgrep:latest semgrep --config auto --json -o /src/semgrep-sast-report.json
      continue-on-error: true

    - name: Upload Semgrep Report
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sast-report
        path: semgrep-sast-report.json

  dependency_check_sca_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Report Directory
      run: mkdir -p dependency-check-sca-report

    - name: Dependency Check Scan
      run: |
        docker pull owasp/dependency-check:9.0.0
        docker run --rm --user=root -v "${{ github.workspace }}:/src" owasp/dependency-check:9.0.0 --scan /src --format JSON --format HTML --out /src/dependency-check-sca-report --prettyPrint
      continue-on-error: true

    - name: Upload Dependency Check Reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-sca-report
        path: |
          dependency-check-sca-report/dependency-check-report.json
          dependency-check-sca-report/dependency-check-report.html

  trivy_image_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Image Scan with Trivy
      run: |
        docker pull ${{ env.DOCKER_IMAGE }}
        docker pull aquasec/trivy:latest
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/home aquasec/trivy:latest image ${{ env.DOCKER_IMAGE }} --format json -o /home/trivy-image-report.json
      continue-on-error: true

    - name: Upload Trivy Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-report
        path: trivy-image-report.json

  checkov_iac_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkov Scan
      run: |
        docker pull bridgecrew/checkov:3.2.401
        docker run --volume ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov:3.2.401 --directory /tf -o cli -o json --output-file-path console,checkov-iac-report.json --skip-resources-without-violations --quiet --compact
      continue-on-error: true

    - name: Upload Checkov Report
      uses: actions/upload-artifact@v4
      with:
        name: checkov-iac-report
        path: checkov-iac-report.json
